AWSTemplateFormatVersion: "2010-09-09"
Description: container on ECS cluster

Resources:
  Task:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: GamestoreApi
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue EcsTaskExecutionRole
      ContainerDefinitions:
        - Name: GamestoreApi
          Image: 990470226174.dkr.ecr.us-east-2.amazonaws.com/diploma:v1
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: 'logGroup'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: 'GamestoreApi'

  Service:
    Type: "AWS::ECS::Service"
    DependsOn: ListenerRule
    Properties:
      ServiceName: gamestore-service
      TaskDefinition: !Ref Task
      Cluster: !ImportValue ECSCluster
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 70
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue OnlineStoreSubnet1
            - !ImportValue OnlineStoreSubnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: GamestoreApi
          ContainerPort: 80
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: gamestore-tg
      VpcId: !ImportValue OnlineStoreVpc
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /swagger
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: "AWS::ElasticLoadBalancingV2::ListenerRule"
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /api*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:
  Api:
    Description: Endpoint for api
    Value: !Join
      - ''
      - - 'http://'
        - Fn::ImportValue: DomainName
        - '/api'
    Export:
      Name: GamestoreApiEndpoint